- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: Check whether Nginx service start or not
      stat:
        path: /var/run/nginx.pid
      register: nginx_pid_file

    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        cache_valid_time: 3600
      when: not nginx_pid_file.stat.exists
    
    - name: Start Nginx
      shell: |
        nginx
      when: not nginx_pid_file.stat.exists
      
    - name: Copy Nginx config file
      copy: 
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
      
    - name: Enable configuration
      file: 
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link
    
    - name: Copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644
    
    - name: Restart Nginx
      shell: |
        nginx -s reload
